### ISSUE TITLE
Incompability with a mod

### ISSUE THREAD

**Issue by bauerwilhelm** [RuochenFu21/CreateLiquidFuel#13] opened 2024-01-26 16:14 UTC
[crash-2024-01-26_17.08.55-fml.txt](https://github.com/RuochenFu21/CreateLiquidFuel/files/14067032/crash-2024-01-26_17.08.55-fml.txt)

I suppose there is a incompability issue with something but I can't identify what exactly. Maybe you want to have a look into it. If you know what it is maybe you want to fix it or put an info in the mod describtion.

Love your work!

**Comment by DoigtdePOULET** [comment] 2024-01-26 19:49
I have exactly the same error, just from today. I suspect an incompatibility betwen mods versions. Here is the list of updates from today: 

PuzzlesLib-v8.1.14-1.20.1-Forge
L_Enders_Cataclysm-1.90 -1.20.1
sootychimneys-1.20.1-1.2.1
geckolib-forge-1.20.1-4.4.2
domum_ornamentum-1.20-1.0.154-BETA-universal
decorative_blocks-forge-1.20.1-4.1.1******************** My guess is this one... I'll check if I can boot without it. 
cratedelight-1.0.2-1.20.1
blockui-1.20.1-1.0.135-BETA
betterchunkloading-1.20.1-3.2
balanced_crates-1.7.71 (1.20.1)
thornybushprotection-1.20.1-1.2
wooltostring-forge-1.20.1-v1.1.0
drizzleproof-1.20.1-2.0.0

**Comment by DoigtdePOULET** [comment] 2024-01-26 19:55
Exactly that! Server boots without issues, by removing decorative_blocks-forge-1.20.1-4.1.1

I'll try with an another version of the mod (It was working yesterday)

**Comment by bauerwilhelm** [comment] 2024-01-27 09:43
Yep, seems to be decorative blocks. I tried with the older version and it works again.

**Comment by bauerwilhelm** [comment] 2024-02-02 09:25
Will you look into it? Decorative blocks keeps getting updates and changes, which we can't use if it doesn't work with LiquidFuel :(

**Comment by Caldoric** [comment] 2024-02-03 10:22
Well, the mod creator is being annoyingly unhelpful on Curseforge and keeps demanding I talk to them here instead of on the Curseforge site, so, whatever...

From what I've seen regarding the cross-mod conflict, there's some kind of "java.lang.NullPointerException" error when trying to load the two mods together, which states that a "registry object" by the name of "decorative_blocks:lattice" is not present...

Honestly, dude should just talk to the author/coder for Decorative Blocks so they can work out whatever is going on here. The two mods were working together just fine until a recent update on DB's part. I even poked them about it after I first noticed the issue, and they told me to talk to the author of C:LF because the issue had something to do with C:LF's code or whatever, but at this point I don't care, I'm not a fucking messenger owl! You lot talk it out and get it fixed, however that ends up happening.

**Comment by furuochen-dev** [comment] 2024-02-03 10:23
Could be duplicate of #12

**Comment by Caldoric** [comment] 2024-02-03 10:25
No, because the item mentioned in the crash report was a solid block, not a liquid.

**Comment by bauerwilhelm** [comment] 2024-02-03 10:25
Understood. I was just confused because of the "completed" :)

**Comment by furuochen-dev** [comment] 2024-02-03 10:26
> No, because the item mentioned in the crash report was a solid block, not a liquid.

It's having to do with the mechanic of the mod

**Comment by Caldoric** [comment] 2024-02-03 10:27
Well whatever it is, the authors of the two mods need to talk it out and see what's up. I'm not part of this.

**Comment by furuochen-dev** [comment] 2024-02-03 10:28
Welp, definitely a duplicate of #12

**Closed as completed by furuochen-dev** 2024-02-03 10:28 UTC

**Comment by furuochen-dev** [comment] 2024-02-03 10:29
> Well whatever it is, the authors of the two mods need to talk it out and see what's up. I'm not part of this.

That's not what we usually do with incompatiblities, but thanks for the advice I guess

**Comment by Caldoric** [comment] 2024-02-03 10:34
> That's not what we usually do with incompatiblities, but thanks for the advice I guess

Why not? That's the only sensible option. If folks talk and work stuff out, they can potentially avoid future incompatibilities coming up again.

**Comment by furuochen-dev** [comment] 2024-02-03 10:36
> > That's not what we usually do with incompatiblities, but thanks for the advice I guess
> > Why not? That's the only sensible option. If folks talk and work stuff out, they can potentially avoid future incompatibilities coming up again.

Y'know, I can just fix this issue on my side... And I don't like to disturb people

**Comment by bauerwilhelm** [comment] 2024-02-03 10:36
Why we being so unpolite now😅 Don't start your Sunday Morning like that

**Comment by furuochen-dev** [comment] 2024-02-03 10:38
> Why we being so unpolite now😅 Don't start your Sunday Morning like that

Welp, sorry if this keep sending you email because you subscribed to the issue, you can unsubscribe this one, and if you want to be informed about further updates, subscribing to #12 is an option for you😄

**Comment by furuochen-dev** [comment] 2024-02-03 10:42
> > That's not what we usually do with incompatiblities, but thanks for the advice I guess
> 
> Why not? That's the only sensible option. If folks talk and work stuff out, they can potentially avoid future incompatibilities coming up again.

It looks like the owner of decorative block is the owner of that issue
